services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    ports:
      - '5432:5432' # postges port
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=financial_advisor_ai
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/pgdata
    volumes:
      - ~/.jump/pgvector:/var/lib/postgresql/pgdata
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
